//  <auto-generated/> 
using Rido.IoTHubClient;
using System.Text.Json;

namespace dtmi_rido_pnp;

public enum DiagnosticsMode
{
    minimal = 0,
    complete = 1,
    full = 2
}

public class Cmd_getRuntimeStats_Request : IBaseCommandRequest
{
    public int _rid { get; set; }
    public DiagnosticsMode DiagnosticsMode { get; set; }

    public object Deserialize(string payload)
    {
        return new Cmd_getRuntimeStats_Request()
        {
            DiagnosticsMode = JsonSerializer.Deserialize<DiagnosticsMode>(payload)
        };
    }
}


