//  <auto-generated/> 
using System.Collections.Generic;

namespace dtmi_rido_pnp_sample;

public class Cmd_getRuntimeStats_Response : Dictionary<string, string>
{
    public int? Status { get; set; }
}
