//  <auto-generated/> 
#nullable enable

using Rido.IoTHubClient;
using Rido.IoTHubClient.TopicBinders;

namespace dtmi_rido_pnp_sample
{
    public class memmon : BasicHubClient
    {
        const string modelId = "dtmi:rido:pnp:sample:memmon;1";

        public ReadOnlyProperty<DateTime> Property_memMon_started { get; private set; }
        public WritableProperty<bool> Property_memMon_enabled;
        public WritableProperty<int> Property_memMon_interval;
        public CommandBinder<Cmd_getRuntimeStats_Request, Cmd_getRuntimeStats_Response> Command_getRuntimeStats_Binder;

        private memmon(IMqttConnection c) : base(c)
        {
            Property_memMon_started = new ReadOnlyProperty<DateTime>(c, "started", "memMon");
            Property_memMon_enabled = new WritableProperty<bool>(c, "enabled", "memMon");
            Property_memMon_interval = new WritableProperty<int>(c, "interval", "memMon");
            Command_getRuntimeStats_Binder = new CommandBinder<Cmd_getRuntimeStats_Request, Cmd_getRuntimeStats_Response>(c, "getRuntimeStats", "memMon");
        }

        public static async Task<memmon> CreateDeviceClientAsync(string cs, CancellationToken cancellationToken)
        {
            ArgumentNullException.ThrowIfNull(cs);
            var connection = await HubMqttConnection.CreateAsync(new ConnectionSettings(cs) { ModelId = modelId }, cancellationToken);
            var client = new memmon(connection);
            client.InitialTwin = await client.GetTwinAsync();
            return client;
        }
        public async Task<PubResult> Send_memMon_workingSet_Async(double workingSet, CancellationToken cancellationToken =default) => 
            await base.SendTelemetryAsync(new { workingSet }, "memMon", cancellationToken);
        
    }
}
