//  <auto-generated/> 
#nullable enable

using MQTTnet;
using MQTTnet.Client;
using MQTTnet.Client.Publishing;
using MQTTnet.Client.Subscribing;
using MQTTnet.Protocol;
using Rido.IoTHubClient;
using System.Diagnostics;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Web;

public class CommandResponse
{
    [JsonIgnore]
    public int _status { get; set; }
    [JsonIgnore]
    public int _rid { get; set; }
}

public class TargetTemperature
{
    public double targetTemperature { get; set; }
    public int version { get; set; }
}

public class Command_getMaxMinReport_Request
{
    public DateTime since { get; set; }
    public int _rid { get; set; }
}

public class Command_getMaxMinReport_Response : CommandResponse
{
    public double maxTemp { get; set; }
    public double minTemp { get; set; }
    public double avgTemp { get; set; }
    public DateTimeOffset startTime { get; set; }
    public DateTimeOffset endTime { get; set; }
}

public class Thermostat
{
    int lastRid = 0;
    IMqttClient? client = null;
    ConnectionSettings? dcs = null;

    public Func<TargetTemperature, PropertyAck>? OntargetTemperatureUpdated = null;

    public Func<Command_getMaxMinReport_Request, Command_getMaxMinReport_Response>? Command_getMaxMinReport = null;


    public Thermostat(string cs)
    {
        client = new MqttFactory().CreateMqttClient();
        dcs = ConnectionSettings.FromConnectionString(cs);
        var connack = client.ConnectWithSasAsync(dcs.HostName, dcs.DeviceId, dcs.SharedAccessKey, "dtmi:com:example:Thermostat;1", 5).Result;
        Console.WriteLine(connack.ResultCode);
        Configure().Wait();
    }

    public Thermostat(IMqttClient c, ConnectionSettings cs)
    {
        client = c;
        dcs = cs ?? throw new ArgumentNullException(nameof(cs));
        Configure().Wait();
    }

    async Task Configure()
    {
        var subres = await client.SubscribeAsync(new MqttClientSubscribeOptionsBuilder()
                                                   .WithTopicFilter("$az/iot/methods/+/+", MqttQualityOfServiceLevel.AtLeastOnce)
                                                   .WithTopicFilter("$az/iot/twin/get/response/+", MqttQualityOfServiceLevel.AtLeastOnce)
                                                   .WithTopicFilter("$az/iot/twin/patch/response/+", MqttQualityOfServiceLevel.AtLeastOnce)
                                                   .WithTopicFilter("$az/iot/twin/events/desired-changed/+", MqttQualityOfServiceLevel.AtLeastOnce)
                                                   .Build());
        subres.Items.ToList().ForEach(x => Trace.TraceInformation($"+ {x.TopicFilter.Topic} {x.ResultCode}"));

        if (subres.Items.ToList().Any(x => x.ResultCode == MqttClientSubscribeResultCode.UnspecifiedError))
        {
            throw new ApplicationException("Error subscribing to system topics");
        }

        client.UseApplicationMessageReceivedHandler(async m =>
        {
            var segments = m.ApplicationMessage.Topic.Split('/');
            int rid = 0;
            int twinVersion = 0;
            if (m.ApplicationMessage.Topic.Contains("?"))
            {
                // parse qs to extract the rid
                var qs = HttpUtility.ParseQueryString(segments[^1]);
                rid = Convert.ToInt32(qs["rid"]);
                twinVersion = Convert.ToInt32(qs["v"]);
            }

            string msg = string.Empty;
            if (m.ApplicationMessage.Topic.StartsWith("$az/iot/twin/events/desired-changed"))
            {
                msg = Encoding.UTF8.GetString(m.ApplicationMessage.Payload ?? Array.Empty<byte>());
                JsonElement targetTemperature = JsonDocument.Parse(msg).RootElement.GetProperty("targetTemperature");
                var ack = OntargetTemperatureUpdated?.Invoke(new TargetTemperature { targetTemperature = targetTemperature.GetDouble(), version = twinVersion });
                if (ack != null) await this.Report_targetTemperatureACK(ack);
            }

            if (m.ApplicationMessage.Topic.StartsWith("$az/iot/twin/patch/response/"))
            {
                msg = Encoding.UTF8.GetString(m.ApplicationMessage.Payload ?? Array.Empty<byte>());
                Callback_maxTempSinceLastReboot?.Invoke(twinVersion);
            }

            if (m.ApplicationMessage.Topic.StartsWith("$az/iot/methods/getMaxMinReport"))
            {
                msg = Encoding.UTF8.GetString(m.ApplicationMessage.Payload ?? Array.Empty<byte>());
                var resp = Command_getMaxMinReport?.Invoke(
                    new Command_getMaxMinReport_Request { since = JsonSerializer.Deserialize<DateTime>(msg), _rid = rid });
                await client.PublishAsync($"$az/iot/methods/getMaxMinReport/response/?rid={resp?._rid}&rc={resp?._status}", JsonSerializer.Serialize(resp));
            }
        });
    }



    Action<int>? Callback_maxTempSinceLastReboot = null;
    public async Task<int> Report_maxTempSinceLastReboot(double temperature)
    {
        var tcs = new TaskCompletionSource<int>();
        var puback = await client.PublishAsync(
            $"$az/iot/twin/patch/reported/?rid={lastRid++}",
            JsonSerializer.Serialize(new { maxTempSinceLastReboot = temperature }));
        if (puback.ReasonCode == MqttClientPublishReasonCode.Success)
        {
            Callback_maxTempSinceLastReboot = s => tcs.TrySetResult(s);
        }
        else
        {
            Callback_maxTempSinceLastReboot = s => tcs.TrySetException(new ApplicationException($"Error '{puback.ReasonCode}' publishing twin PATCH: {s}"));
        }
        return tcs.Task.Result;
    }

    public async Task<MqttClientPublishResult> Send_temperature(double temperature)
    {
        return await client.PublishAsync(
            $"$az/iot/telemetry",
            JsonSerializer.Serialize(new { temperature }));
    }


    public async Task Report_targetTemperatureACK(PropertyAck ack)
    {
        var puback = await client.PublishAsync(
           $"$az/iot/twin/patch/reported/?rid={lastRid++}", ack.BuildAck());
    }
}

